### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mcquiggd** [lmaccherone/documentdb-lumenize#1]
Hi,

interesting project.

I noticed that the original Lumenize is MIT Licensed, but this implementation for DocumentDB is not.

I also do notice it says to contact you regarding 'other uses' (i.e. commercial), but can you possibly give some outline of your intentions regarding licensing of this project?

**Comment by lmaccherone** [comment]
I license it commercially on a case-by-case basis. I suggest that you try it out and if you find it useful, please make me an offer indicating what you think is fair. In general, I prefer annual licenses. Also, open to making bountied upgrades and working with your development team to utilize.
