### ISSUE TITLE
Continuation always NULL and stillQueueing is True

### ISSUE THREAD

**Issue by sbosell** [lmaccherone/documentdb-lumenize#5]
Whenever I run the stored procedure it always return an empty set, null continuation, and stillqueuing is true.   

The document looks like this:

```
{
  "id": "52129314",
  "BlastKey": "m-857459",
  "BlastLinkJobId": 52129314,
  "JobId": 399597,
  "MemberId": 857459,
  "BlastLinkId": 7927,
  "Date": {
    "Date": "2017-01-18T13:04:19-05:00",
    "Epoch": 1484744659
  },
  "UserIpAddress": "1.1.1.1",
  "LocationId": 1802,
  "LinkHref": "http://www.abc.com",
  "LinkType": 2,
  "BlastId": 1375,
  "DocumentType": 0
}

```

Here is an example:

```
{
  "cubeConfig": {
    "groupBy": "LocationId",
    "field": "id",
    "f": "count"
  },
  "filterQuery": "SELECT c.LocationId, c.id FROM c",
  "continuation": null,
  "stillQueueing": true,
  "savedCube": {
    "config": {
      "groupBy": "LocationId",
      "field": "id",
      "f": "count"
    },
    "cellsAsCSVStyleArray": [],
    "summaryMetrics": {}
  }
}

```

**Comment by 5mdd** [comment]
@sbosell I have exactly the same issue. The stored procedure works nicely on databases that are not partitioned... but fails on my partitioned cosmosdb sql collection.
Did you manage to find a solution to this issue?
`{'filterQuery': "SELECT * FROM c ",
 'cubeConfig': {'groupBy': 'mid', 'field': 'us_avg', 'f': 'count'},
 'continuation': None,
 'stillQueueing': True,
 'savedCube': {'config': {'groupBy': 'mid',
   'field': 'us_avg',
   'f': 'count'},
  'cellsAsCSVStyleArray': [],
  'summaryMetrics': {}}}`

**Comment by 5mdd** [comment]
I elaborated a bit more on this issue here: [https://github.com/MicrosoftDocs/azure-docs/issues/24801#issuecomment-462962687](https://github.com/MicrosoftDocs/azure-docs/issues/24801#issuecomment-462962687)
If either @sbosell or @lmaccherone could give some feedback on this, it would be much appreciated 👍
I suspect an issue dealing with the partitioning of a container... any feedback to that respect?

**Comment by lmaccherone** [comment]
When you call the sproc, does the options object have something like, `{partitionKey: items[0].partiionkeyfield}`? The partition key needs to look exactly like the field, so don't hand build it (your question about it needing a slash or not), rather pull it from one of the records. Alternatively, you can query for the partitioning table and use the first entry in the partitioning table (which is inclusive), but that's a lot more complicated.
